Repository hlmod/Shop-Core, pull requests merged in 2022-04, with the labels that each got.

#87 Adding Methodmaps. Issue #10
  addons/sourcemod/scripting/include/shop.inc
  addons/sourcemod/scripting/include/shop/methodmaps.inc
  addons/sourcemod/scripting/shop/item_manager.sp
  addons/sourcemod/scripting/shop/player_manager.sp
Labels: Enhancement

#121 Added forward Shop_OnItemRegistered
  addons/sourcemod/scripting/include/shop/register.inc
  addons/sourcemod/scripting/shop/forwards.sp
  addons/sourcemod/scripting/shop/item_manager.sp
Labels: Enhancement

#118 Added Reworked Version of Confirm Purchase function, and Confirm Try a Luck function
  addons/sourcemod/scripting/shop.sp
  addons/sourcemod/scripting/shop/functions.sp
  addons/sourcemod/scripting/shop/item_manager.sp
  addons/sourcemod/translations/ru/shop.phrases.txt
  addons/sourcemod/translations/shop.phrases.txt
  cfg/shop/shop.cfg
Labels: Enhancement, In progress

#97 Fix sort categories
  addons/sourcemod/scripting/shop/item_manager.sp
Labels: Test needed
